site_name: Documentation
site_description: Documentation for k0s, the Zero friction Kubernetes distribution.
site_author: Mirantis, Inc.
site_url: https://docs.k0sproject.io
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/k0sproject/k0s
copyright:
  Copyright &copy; 2021 <a href="https://mirantis.com/">Mirantis Inc.</a>
  - All rights reserved.
edit_uri: ""
nav:
  - Overview: README.md
  - Installation:
      - Quick Start Guide: install.md
      - Using k0sctl: k0sctl-install.md
      - Alternative Methods:
          - Manual (advanced): k0s-multi-node.md
          - Docker: k0s-in-docker.md
          - Windows (experimental): experimental-windows.md
          - Raspberry Pi 4: raspberry-pi4.md
          - Ansible Playbook: examples/ansible-playbook.md
          - Airgap Install: airgap-install.md
          - Using custom CA certificate (advanced): custom-ca.md
      - System Requirements: system-requirements.md
      - External runtime dependencies: external-runtime-deps.md
  - Maintenance:
      - Upgrade: upgrade.md
      - Backup/Restore: backup.md
      - Remove/Replace a controller: remove_controller.md
      - Uninstall: reset.md
  - Usage:
      - Configuration Options: configuration.md
      - Dynamic Configuration: dynamic-configuration.md
      - Configuration Validation: configuration-validation.md
      - Worker Node Configuration: worker-node-config.md
      - Networking (CNI): networking.md
      - Runtime (CRI): runtime.md
      - Storage (CSI): storage.md
      - System Components Monitoring: system-monitoring.md
      - Manifest Deployer: manifests.md
      - Helm Charts: helm-charts.md
      - Cloud Providers: cloud-providers.md
      - IPv4/IPv6 Dual-Stack: dual-stack.md
      - Control Plane High Availability: high-availability.md
      - Node-local load balancing: nllb.md
      - Shell Completion: shell-completion.md
      - User Management: user-management.md
      - Configuration of Environment Variables: environment-variables.md
      - OpenID Connect: ./examples/oidc/oidc-cluster-configuration.md
      - SELinux: selinux.md
      - Pod Security Standards: podsecurity.md
      - Re-install: reinstall-k0sctl.md
  - Auto Updates:
      - Overview: autopilot.md
      - Multi-Command Plans: autopilot-multicommand.md
  - Extensions:
      - MetalLB Load Balancer: examples/metallb-loadbalancer.md
      - NGINX Ingress Controller: examples/nginx-ingress.md
      - Traefik Ingress Controller: examples/traefik-ingress.md
      - Ambassador API Gateway: examples/ambassador-ingress.md
      - Ceph Storage with Rook: examples/rook-ceph.md
      - GitOps with Flux: examples/gitops-flux.md
  - Troubleshooting:
      - FAQ: FAQ.md
      - Common Pitfalls: troubleshooting.md
  - Reference:
      - Architecture: architecture.md
      - Kube-bench Security Benchmark: cis_benchmark.md
  - Releases: releases.md
  - Contributing:
      - Overview: contributors/overview.md
      - GitHub Workflow: contributors/github_workflow.md
      - Testing: contributors/testing.md
      - Documentation: internal/publishing_docs_using_mkdocs.md

theme:
  name: "material"
  highlightjs: true
  language: "en"
  custom_dir: docs/custom_theme
  favicon: img/k0s_social.png
  logo: img/k0s_social.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - toc.autohide
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - macros:
      j2_variable_start_string: "{{{"
      j2_variable_end_string: "}}}"
  - exclude:
      glob:
        - "*.etag"
        - Dockerfile.serve-dev
        - k0s
        - k0s.exe
        - Makefile*
        - requirements_pip.txt
        - requirements.txt

markdown_extensions:
  - pymdownx.highlight: {}
  - pymdownx.superfences: {}
  - pymdownx.inlinehilite: {}
  - mdx_truly_sane_lists: # https://github.com/mkdocs/mkdocs/issues/545#issuecomment-522196661
      nested_indent: 2
      truly_sane: true
  - toc:
      permalink: "#"
      toc_depth: 3
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  k8s_version: !!python/object/apply:os.getenv ["KUBE_VERSION"]
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/k0sproject/k0s
      name: k0s on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/k0sproject
      name: k0s on Twitter
    - icon: fontawesome/brands/slack
      link: http://k8slens.slack.com/
      name: k0s on Slack
    - icon: fontawesome/solid/link
      link: https://k0sproject.io/
      name: k0s Website
  version:
    provider: mike
    default: stable
