site_name: Documentation
site_description: Documentation for k0s, the Zero friction Kubernetes distribution.
site_author: Mirantis, Inc.
site_url: https://docs.k0sproject.io
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/k0sproject/k0s
copyright: Copyright &copy; 2021 <a href="https://mirantis.com/">Mirantis Inc.</a>
    - All rights reserved.
edit_uri: ""
nav:
  - Overview: README.md
  - Install:
      - Quick Start Guide:                install.md
      - Install using k0sctl:             k0sctl-install.md
      - Alternative Install Methods:
          - Manual Install (advanced):    k0s-multi-node.md
          - Docker:                       k0s-in-docker.md
          - Windows (experimental):       experimental-windows.md
          - Raspberry Pi 4:               raspberry-pi4.md
          - Ansible Playbook:             examples/ansible-playbook.md
          - Airgap Install:               airgap-install.md
      - Upgrade:                          upgrade.md
      - Backup/Restore:                   backup.md
      - Uninstall/Reset:                  reset.md
      - System Requirements:              system-requirements.md
  - Usage:
      - Configuration Options:            configuration.md
      - Configuration Validation:         configuration-validation.md
      - Worker Node Configuration:        worker-node-config.md
      - Networking (CNI):                 networking.md
      - Runtime (CRI):                    runtime.md
      - Storage (CSI):                    storage.md
      - Cloud Providers:                  cloud-providers.md
      - IPv4/IPv6 Dual-Stack:             dual-stack.md
      - Control Plane High Availability:  high-availability.md
      - Shell Completion:                 shell-completion.md
      - User Management:                  user-management.md
  - Extensions:
      - Manifest Deployer:                manifests.md
      - Helm Charts:                      helm-charts.md
      - Examples:
          - Traefik Ingress Controller:   examples/traefik-ingress.md
          - Ambassador Gateway:           examples/ambassador-ingress.md
          - Ceph Storage with Rook:       examples/rook-ceph.md
  - Troubleshooting:
      - FAQ:                              FAQ.md
      - Common Pitfalls:                  troubleshooting.md
  - Reference:
      - Architecture:                     architecture.md
      - CIS Benchmark:                    cis_benchmark.md
  - Contributing:
      - Overview:                         contributors/overview.md
      - GitHub Workflow:                  contributors/github_workflow.md
      - Testing:                          contributors/testing.md
      - Documentation:                    internal/publishing_docs_using_mkdocs.md

theme:
    name: 'material'
    highlightjs: true
    language: 'en'
    custom_dir: docs/custom_theme
    favicon: img/k0s_social.png
    logo: img/k0s_social.png
    palette:
      - scheme: default
        toggle:
            icon: material/toggle-switch
            name: Switch to light mode
      - scheme: slate
        toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
    features:
      - toc.autohide
      - search.suggest
      - search.highlight

extra_css:
  - stylesheets/extra.css
plugins:
  - search

markdown_extensions:
  - pymdownx.highlight: {}
  - pymdownx.superfences: {}
  - pymdownx.inlinehilite: {}
  - toc:
        permalink: "#"
        toc_depth: 3

extra:
    generator: false
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/k0sproject/k0s
        name: k0s on GitHub
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/k0sproject
        name: k0s on Twitter
      - icon: fontawesome/brands/slack
        link: http://k8slens.slack.com/
        name: k0s on Slack
      - icon: fontawesome/solid/link
        link: https://k0sproject.io/
        name: k0s Website
    version:
      method: mike
