name: Build docs

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - "**.md"
      - docs/**
      - embedded-bins/Makefile.variables
      - pkg/constant/constant.go
      - mkdocs.yml
      - vars.sh

  pull_request:
    branches:
      - main
      - release-*
    paths:
      - "**.md"
      - docs/**
      - embedded-bins/Makefile.variables
      - pkg/constant/constant.go
      - mkdocs.yml
      - vars.sh

env:
  MAKEFLAGS: -j

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout k0s
        uses: actions/checkout@v4

      - name: Prepare build environment
        run: .github/workflows/prepare-build-env.sh

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: docs/requirements.txt

      - name: Install dependencies
        run: |
          # https://github.com/actions/setup-python/issues/521
          # https://github.com/actions/python-versions/blob/3.10.9-3636985951/installers/nix-setup-template.sh#L53
          pip install --disable-pip-version-check -r docs/requirements_pip.txt
          pip --version
          pip install --disable-pip-version-check -r docs/requirements.txt

      - name: Generate docs
        env:
          GH_TOKEN: ${{ github.token }}
        run: make -C docs docs

      - name: Upload site/
        uses: actions/upload-artifact@v6
        with:
          name: site
          path: site/

  dev-container:
    name: Build docs dev container
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout k0s
        uses: actions/checkout@v4

      - name: Build docs dev container
        run: make -C docs .docker-image.serve-dev.stamp
