name: Label Top Issues

on:
  schedule:
    - cron:  '15 0-23 * * *'

jobs:
  labelTopIssues:
    name: Label Top Issues
    runs-on: ubuntu-latest
    steps:
      - name: Label Issues
        uses: adamzolyak/top-issues-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOP_NUMBER_OF_ISSUES: 10
          TOP_LABEL_NAME: "üëç Top Issue"
          TOP_LABEL_COLOR: f442c2