name: Update Default Documentation Version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version string to be default (e.g."v0.0.1")'
        required: true
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    name: Update default docs Version
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Checkout deps
        uses: actions/checkout@v3
        with:
          repository: lensapp/mkdocs-material-insiders
          token: ${{ env.GITHUB_TOKEN }}
          path: mkdocs-material-insiders

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./mkdocs-material-insiders
          pip install mdx-truly-sane-lists
          pip install mike

      - name: Checkout Release from k0s
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: mkdocs update default version
        run: |
          mike set-default --push ${{ github.event.inputs.version }}
