name: Manually publish docs via GitHub Pages
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g."v1.26.2+k0s.0")'
        required: true

env:
  PYTHON_VERSION: 3.x
  TARGET_VERSION: ${{ github.event.inputs.version }}

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout k0s main
        uses: actions/checkout@v3
        with:
          ref: main
          path: main
          fetch-depth: 0

      - name: Prepare build environment
        working-directory: ./main
        run: .github/workflows/prepare-build-env.sh

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: docs/requirements.txt

      - name: Install dependencies
        working-directory: ./main
        run: |
          pip install --disable-pip-version-check -r docs/requirements_pip.txt
          pip --version
          pip install --disable-pip-version-check -r docs/requirements.txt

      - name: Checkout k0s ${{ github.event.inputs.version }}
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.version }}'
          fetch-depth: 0

      - name: Copy files from main to ${{ github.event.inputs.version }}
        run: |
          cp -p main/docs/Makefile docs/Makefile
          cp -p main/mkdocs.yml mkdocs.yml
          rm -rf main

      - name: Generate docs
        env:
          GH_TOKEN: ${{ github.token }}
        run: make -C docs docs clean-k0s

      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"


      - name: mike deploy ${{ github.event.inputs.version }}
        run: |
          mike deploy --push --force ${{ github.event.inputs.version }}
