name: "Close stale PRs"
on:
  schedule:
    - cron: "0 23 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'The issue is marked as stale since no activity has been recorded in 30 days'
          stale-pr-message: 'The PR is marked as stale since no activity has been recorded in 30 days'
          days-before-stale: 30
          close-pr-label: "stale"
          remove-issue-stale-when-updated: true
          remove-pr-stale-when-updated: true
          labels-to-remove-when-unstale: "stale"
          exempt-issue-labels: "enhancement"
