---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: updateconfigs.autopilot.k0sproject.io
spec:
  group: autopilot.k0sproject.io
  names:
    kind: UpdateConfig
    listKind: UpdateConfigList
    plural: updateconfigs
    singular: updateconfig
  scope: Cluster
  versions:
  - name: v1beta2
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              channel:
                default: stable
                description: Channel defines the update channel to use for this update
                  config
                type: string
              planSpec:
                description: PlanSpec defines the plan spec to use for this update
                  config
                properties:
                  commands:
                    description: |-
                      Commands are a collection of all of the commands that need to be executed
                      in order for this plan to transition to Completed.
                    items:
                      description: AutopilotPlanCommand is a command that can be run
                        within a `Plan`
                      properties:
                        airgapupdate:
                          description: AirgapUpdate is the `AirgapUpdate` command
                            which is responsible for updating a k0s airgap bundle.
                          properties:
                            workers:
                              description: Workers defines how the k0s workers will
                                be discovered and airgap updated.
                              properties:
                                discovery:
                                  description: Discovery details how nodes for this
                                    target should be discovered.
                                  properties:
                                    selector:
                                      description: Selector provides a kubernetes
                                        'selector' means of identifying target signal
                                        nodes.
                                      properties:
                                        fields:
                                          description: Fields is a standard kubernetes
                                            field selector (key=value,key=value,...)
                                          type: string
                                        labels:
                                          description: Labels is a standard kubernetes
                                            label selector (key=value,key=value,...)
                                          type: string
                                      type: object
                                    static:
                                      description: Static provides a static means
                                        of identifying target signal nodes.
                                      properties:
                                        nodes:
                                          description: Nodes provides a static set
                                            of target signal nodes.
                                          items:
                                            type: string
                                          type: array
                                      type: object
                                  type: object
                                limits:
                                  default:
                                    concurrent: 1
                                  description: Limits impose various limits and restrictions
                                    on how discovery and execution should behave.
                                  properties:
                                    concurrent:
                                      default: 1
                                      description: |-
                                        Concurrent specifies the number of concurrent target executions that can be performed
                                        within this target. (ie. '2' == at most have 2 execute at the same time)
                                      type: integer
                                  type: object
                              required:
                              - discovery
                              type: object
                          required:
                          - workers
                          type: object
                        k0supdate:
                          description: K0sUpdate is the `K0sUpdate` command which
                            is responsible for updating a k0s node (controller/worker)
                          properties:
                            forceupdate:
                              description: ForceUpdate ensures that version checking
                                is ignored and that all updates are applied.
                              type: boolean
                            targets:
                              description: Targets defines how the controllers/workers
                                should be discovered and upgraded.
                              properties:
                                controllers:
                                  description: Controllers defines how k0s controllers
                                    will be discovered and executed.
                                  properties:
                                    discovery:
                                      description: Discovery details how nodes for
                                        this target should be discovered.
                                      properties:
                                        selector:
                                          description: Selector provides a kubernetes
                                            'selector' means of identifying target
                                            signal nodes.
                                          properties:
                                            fields:
                                              description: Fields is a standard kubernetes
                                                field selector (key=value,key=value,...)
                                              type: string
                                            labels:
                                              description: Labels is a standard kubernetes
                                                label selector (key=value,key=value,...)
                                              type: string
                                          type: object
                                        static:
                                          description: Static provides a static means
                                            of identifying target signal nodes.
                                          properties:
                                            nodes:
                                              description: Nodes provides a static
                                                set of target signal nodes.
                                              items:
                                                type: string
                                              type: array
                                          type: object
                                      type: object
                                    limits:
                                      default:
                                        concurrent: 1
                                      description: Limits impose various limits and
                                        restrictions on how discovery and execution
                                        should behave.
                                      properties:
                                        concurrent:
                                          default: 1
                                          description: |-
                                            Concurrent specifies the number of concurrent target executions that can be performed
                                            within this target. (ie. '2' == at most have 2 execute at the same time)
                                          type: integer
                                      type: object
                                  required:
                                  - discovery
                                  type: object
                                workers:
                                  description: Workers defines how k0s workers will
                                    be discovered and executed.
                                  properties:
                                    discovery:
                                      description: Discovery details how nodes for
                                        this target should be discovered.
                                      properties:
                                        selector:
                                          description: Selector provides a kubernetes
                                            'selector' means of identifying target
                                            signal nodes.
                                          properties:
                                            fields:
                                              description: Fields is a standard kubernetes
                                                field selector (key=value,key=value,...)
                                              type: string
                                            labels:
                                              description: Labels is a standard kubernetes
                                                label selector (key=value,key=value,...)
                                              type: string
                                          type: object
                                        static:
                                          description: Static provides a static means
                                            of identifying target signal nodes.
                                          properties:
                                            nodes:
                                              description: Nodes provides a static
                                                set of target signal nodes.
                                              items:
                                                type: string
                                              type: array
                                          type: object
                                      type: object
                                    limits:
                                      default:
                                        concurrent: 1
                                      description: Limits impose various limits and
                                        restrictions on how discovery and execution
                                        should behave.
                                      properties:
                                        concurrent:
                                          default: 1
                                          description: |-
                                            Concurrent specifies the number of concurrent target executions that can be performed
                                            within this target. (ie. '2' == at most have 2 execute at the same time)
                                          type: integer
                                      type: object
                                  required:
                                  - discovery
                                  type: object
                              type: object
                          required:
                          - targets
                          type: object
                      type: object
                    type: array
                required:
                - commands
                type: object
              updateServer:
                default: https://updates.k0sproject.io
                description: UpdateServer defines the update server to use for this
                  update config
                type: string
              upgradeStrategy:
                description: UpdateStrategy defines the update strategy to use for
                  this update config
                properties:
                  cron:
                    description: |-
                      Cron defines the cron expression for the cron upgrade strategy
                      Deprecated: Cron is deprecated and will eventually be ignored
                    type: string
                  periodic:
                    description: Periodic defines the periodic upgrade strategy
                    properties:
                      days:
                        items:
                          type: string
                        type: array
                      length:
                        type: string
                      startTime:
                        type: string
                    type: object
                  type:
                    description: Type defines the type of upgrade strategy
                    enum:
                    - periodic
                    - cron
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
